version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  server:
    image: "server:latest"
    ports:
      - "8081:81"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - "mongo"