# Steps to deploy the app:
# - Build the Docker image and push it to Docker Hub
# - Deploy the Docker image to EC2 by SSH

name: Deploy All App

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_TAG_SERVER: SERVER-${{ github.sha }}
  IMAGE_TAG_EXAM_UI: EXAM-UI-${{ github.sha }}
  IMAGE_TAG_NGINX: NGINX-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/duolingo-handle:${{ env.IMAGE_TAG_SERVER }} -f server.Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/duolingo-handle:${{ env.IMAGE_TAG_EXAM_UI }} -f examui.Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/duolingo-handle:${{ env.IMAGE_TAG_NGINX }} -f nginx.Dockerfile .

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/duolingo-handle:${{ env.IMAGE_TAG_SERVER }}
          docker push ${{ secrets.DOCKER_USERNAME }}/duolingo-handle:${{ env.IMAGE_TAG_EXAM_UI }}
          docker push ${{ secrets.DOCKER_USERNAME }}/duolingo-handle:${{ env.IMAGE_TAG_NGINX }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Copy docker-compose file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          source: docker-compose.yaml
          target: .
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}

      # Deploy the Docker image to EC2 by SSH
      - name: Deploy the Docker image to EC2 by SSH
        uses: appleboy/ssh-action@master
        env:
          SERVER_IMAGE_NAME: ${{ env.IMAGE_TAG_SERVER }}
          EXAM_UI_IMAGE_NAME: ${{ env.IMAGE_TAG_EXAM_UI }}
          NGINX_IMAGE_NAME: ${{ env.IMAGE_TAG_NGINX }}
          SERVER_ADMIN_EMAIL: ${{ vars.SERVER_ADMIN_EMAIL }}
          SERVER_ADMIN_PASSWORD: ${{ vars.SERVER_ADMIN_PASSWORD }}
          GOOGLE_CLOUD_API_KEY: ${{ secrets.GOOGLE_CLOUD_API_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          envs: SERVER_IMAGE_NAME, EXAM_UI_IMAGE_NAME, NGINX_IMAGE_NAME, SERVER_ADMIN_EMAIL, SERVER_ADMIN_PASSWORD, GOOGLE_CLOUD_API_KEY, OPENAI_KEY
          script: |
            # Remove the previous version of the app, if exists
            docker-compose down
            # Remove all stoped images
            docker system prune -a --force
            # Up the app
            docker-compose up --remove-orphans -d
