# Build electron app for Mac and Windows through github actions.

name: Build Client Apps

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Install python setuptools
        run: pip3 install setuptools

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.1

      - name: Install dependencies
        working-directory: ./electron_app
        run: yarn

      - name: Build Mac App
        run: yarn make:mac

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 16.20.1

  #     - name: Install dependencies
  #       working-directory: ./electron_app
  #       run: yarn

  #     - name: Build Windows App
  #       working-directory: ./electron_app
  #       run: yarn make:win
