# Steps to deploy the app:
# - Build the Docker image and push it to Docker Hub
# - Deploy the Docker image to EC2 by SSH

name: Setup Nginx

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_TAG: SERVER-${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy nginx files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          source: "nginx.conf,nginx_runner.sh"
          target: ./nginx/
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}

      # Deploy the Docker image to EC2 by SSH
      - name: Deploy the Docker image to EC2 by SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
           chmod +x nginx_runner.sh
           ./nginx_runner.sh

